### ISSUE TITLE
Missing support for custom headers

### ISSUE THREAD

**Issue by ivoputzer** [aquiladev/ipfs-action#15]
It would be very useful to be able to specify headers as part of the action's configuration (ie. to authenticate the `IpfsHttpClient`)

https://github.com/ipfs/js-ipfs/tree/master/packages/ipfs-http-client#custom-headers

**would you be open to considering a PR on this feature?**

**Comment by aquiladev** [comment]
sure, I would also add the latest version of `ipfs-http-client` to such a PR

**Comment by ivoputzer** [comment]
@aquiladev I can make a different PR for that too if it helps out :+1:
