### ISSUE TITLE
Issue Adding Package

### ISSUE THREAD

**Issue by jtsmedley** [aquiladev/ipfs-action#45]
I seem to be at a dead end figuring out how to make the node_modules directory build properly in this repo.  Could you please provide some guidance or would you be open to a packing solution such as vercel/ncc?

**Comment by aquiladev** [comment]
@vercel/ncc is a good idea, I'll take a look
currently you need to commit all dependencies (excluding devDependencies), 
before commit you should run command `npm run prune-prod`

**Comment by aquiladev** [comment]
https://github.com/aquiladev/ipfs-action/releases/tag/v0.3.0-alpha.0
