### ISSUE TITLE
[Feature] Allow not pinning in simple IPFS add

### ISSUE THREAD

**Issue by karmanyaahm** [aquiladev/ipfs-action#51]
Hey, thanks for making this action. I'm using it for my docs website: https://github.com/UnifiedPush/documentation/blob/karmanyaahm-patch-3/.github/workflows/main.yml

It would be nice if I could just add the file to IPFS and not pin it. I have a script that automatically adds it to the IPFS MFS later, so pinning is not necessary.

**Comment by aquiladev** [comment]
try https://github.com/aquiladev/ipfs-action/releases/tag/v0.3.1-alpha.2

**Comment by karmanyaahm** [comment]
Thanks :tada:
