### ISSUE TITLE
The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by paulrberg** [aquiladev/ipfs-action#57]
I just integrated this action in my CI workflow, and it worked smoothly. Thanks for creating this.

However, there seems to be a couple warnings in the CI logs after I run this action:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

<img width="1338" alt="Screenshot 2022-12-12 at 7 26 06 PM" src="https://user-images.githubusercontent.com/8782666/207112650-2c76ac67-bf9f-4275-a891-7791fdde67f5.png">

**Comment by aquiladev** [comment]
What version of action do you use?

**Comment by aquiladev** [comment]
Bumped version of `@actions/core` package, it should solve the issue. Try `ipfs-action@v0.3.1`

**Comment by paulrberg** [comment]
I was on `master`, since this is what's used in the examples in the README.

I have now switched to `v0.3.1`, and the warnings went away. Thank you.
