### ISSUE TITLE
How to properly expose the IPFS API for just this action?

### ISSUE THREAD

**Issue by markg85** [aquiladev/ipfs-action#6]
Hi,

If you're running an IPFS node locally i "think" the API is only exposed for you on the local network.
If you run an IPFS node in docker (and follow the advice in the [docker ipfs page](https://hub.docker.com/r/ipfs/go-ipfs/)) then you too only get an API that is exposed locally.

I don't think one would want to have a public API unless you willingly do just that.

So that leaves the question. How to properly expose the IPFS API so that it can be used for this action alone?
An alternative way seems to be to use nginx as reverse authentication proxy like [this](https://auth0.com/blog/use-nginx-plus-and-auth0-to-authenticate-api-clients/).

I hope you have some advice on how to do this!

Cheers,
Mark

**Comment by aquiladev** [comment]
I think nginx would work.
You may also check https://github.com/marketplace/actions/ipfs-setup-action 
The GitHub action can spin up IPFS node, which you can use in a pipeline, but I did not try it.
